name = "golden-chains-front"
main = "src/app/page.tsx"
compatibility_date = "2024-02-20"

[build]
command = "npm run build"

[site]
bucket = ".next/static"

[[routes]]
pattern = "/*"
custom_domain = false

[[routes]]
pattern = "/_next/*"
custom_domain = false

[[routes]]
pattern = "/api/*"
custom_domain = false 