name = "golden-chains-front"
main = "src/app/page.tsx"
compatibility_date = "2024-02-20"

[build]
command = "npm run build"
output = ".next"

[build.upload]
format = "service-worker"

[site]
bucket = ".next/static"
entry-point = "src/app/page.tsx"

[[routes]]
pattern = "/*"
file = ".next/server/pages/index.html"

[[routes]]
pattern = "/_next/*"
file = ".next/static/*"

[[routes]]
pattern = "/api/*"
file = ".next/server/pages/api/*" 